function [lat, lon, h] = convertManeuver_ENU2WGS84(Trajectory,latLonHRef)

[lat, lon, h] = enu2geodetic(...
    Trajectory.x.Value,...
    Trajectory.y.Value,...
    Trajectory.z.Value,...
    latLonHRef(1),latLonHRef(2),latLonHRef(3),...
    wgs84Ellipsoid);