function [xE, yN, zU] = convertManeuver_WGS842ENU(Trajectory,latLonHRef)

[xE, yN, zU] = geodetic2enu(...
    Trajectory.lat.Value,...
    Trajectory.lon.Value,...
    Trajectory.h.Value,...
    latLonHRef(1),latLonHRef(2),latLonHRef(3),...
    wgs84Ellipsoid);